---
- - :approve
  - "@erquhart/browserify-fs"
  - :who:
    :why: MIT
    :versions: []
    :when: 2025-11-07 13:17:23.330561500 Z
- - :approve
  - indexof
  - :who:
    :why: MIT
    :versions: []
    :when: 2025-11-07 13:17:48.295515500 Z
